on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - uses: aviate-labs/setup-dfx@v0.3.2
        with:
          dfx-version: 0.18.0
          pocket-ic-version: release-2024-04-24_23-01-base
      - run: mv ic/testdata/networks.json $HOME/.config/dfx/networks.json
      - run: make test
