on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - uses: aviate-labs/setup-dfx@v0.3.1
        with:
          dfx-version: 0.18.0
          pocketic-version: 3.0.1
      - run: mv ic/testdata/networks.json $HOME/.config/dfx/networks.json
      - run: make test
