on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.13.1
      - run: make test
